# when running test local, you can specify the image version using the env var REDIS_VERSION.
# Example: ZK_VERSION=3.59 make

services:
  zookeeper:
    image: zookeeper:${ZK_VERSION:-3.4.14}
    container_name: zookeeper
    healthcheck:
      test: nc -z localhost 2181 || exit 1
    ports:
      - "2181:2181"
