version: "3.9"

# when running test local, you can specify the image version using the
# <service>_VERSION.
# Example, to run consul with the version 1.8:
# CONSUL_VERSION=1.8 make

services:
  zookeeper:
    image: zookeeper:${ZK_VERSION:-3.4.14}
    container_name: zookeeper
    healthcheck:
      test: nc -z localhost 2181 || exit 1
    ports:
      - "2181:2181"
